### ISSUE TITLE
The relay device not properly detected by h/w ID

### ISSUE THREAD

**Issue by pavel-a** [patrickjahns/simpleusbrelay#2]
This h/w ID (idVendor=16c0, idProduct=05df) does not identify relay devices! This ID can be shared by various HID devices based on V-USB firmware: http://www.obdev.at/products/vusb/

Their documentation explains how to detect specific device (basically, must read and match the HID string descriptors). These relays have also "serial number" to distinguish among several devices. Your code will use the 1st found device. I'm trying to scratch together a C library [here](https://github.com/pavel-a/usb-relay-hid).

Regards,
-- pa

**Comment by patrickjahns** [comment]
Thanks for the information.
When building the small library I didn`t realize this - I will look into it

**Comment by pavel-a** [comment]
I have only few of them, don't know about others. In my version I've decided to ignore the "vendor" string and check only for "USBRELAY" in the device id, though this is against the usage rules of V-USB free ID.

Regards,
P.

**Comment by patrickjahns** [comment]
Thanks for the info - I will keep it in mind - for now I won`t change it, Any patch is more than welcome
